# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- azure-pipelines

pr:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
      variables:
        CONAN_USE_DOCKER: 1
    macHighSierra:
      imageName: "macos-10.13"
    mac:
      imageName: "macos-10.14"
    windows:
      imageName: "vs2017-win2016"
      variables:
        CONAN_VISUAL_VERSIONS: 15
  maxParallel: 4

pool:
  vmImage: $(imageName)


steps:
# Maven
# Build, test, and deploy with Apache Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'EQHazard/pom.xml' 
    goals: 'package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    
    
# CMake
# Build with the CMake cross-platform build system
- task: CMake@1
  displayName: CMake Configuration
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '..'
    
# CMake
# Build with the CMake cross-platform build system
- task: CMake@1
  displayName: CMake Build
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '--build .'

- script: |
    pip install conan --upgrade
    pip install conan_package_tools bincrafters_package_tools
    conan user
    python build.py
  displayName: Conan Packaging
